-- AlterTable
ALTER TABLE "Trade" ALTER COLUMN "embedding" SET DEFAULT NULL,
ALTER COLUMN "accountBalance" SET DEFAULT NULL,
ALTER COLUMN "accountEquity" SET DEFAULT NULL,
ALTER COLUMN "marginUsed" SET DEFAULT NULL,
ALTER COLUMN "accountLeverage" SET DEFAULT NULL,
ALTER COLUMN "marginLevel" SET DEFAULT NULL,
ALTER COLUMN "freeMargin" SET DEFAULT NULL,
ALTER COLUMN "dailyReturn" SET DEFAULT NULL;
